name: Build CV
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_typst_pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system fonts
        run: |
          set -euxo pipefail
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            fonts-firacode fonts-dejavu poppler-utils unzip fontconfig curl
          sudo fc-cache -f

      - name: Install Fira Sans (Google Fonts)
        run: |
          set -euxo pipefail
          sudo mkdir -p /usr/local/share/fonts/fira
          curl -L \
            "https://fonts.google.com/download?family=Fira%20Sans" \
            -o /tmp/FiraSans.zip
          unzip -q /tmp/FiraSans.zip -d /tmp/fira
          sudo find /tmp/fira -type f -iname "*.ttf" \
            -exec cp -n {} /usr/local/share/fonts/fira/ \;
          sudo fc-cache -f
          echo "Installed Fira fonts:"
          fc-list | grep -i "fira" | head -n 20 || true

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Verify font discovery
        run: |
          set -euxo pipefail
          typst fonts | grep -Eiq "^fira( |$)" || {
            echo "Typst cannot see Fira fonts"; exit 1; }

      - name: Compile CV
        run: typst compile english.typ english.pdf

      - name: Upload artifact (PR or push)
        uses: actions/upload-artifact@v4
        with:
          name: English-PDF-${{ github.event_name }}-${{ github.run_number }}
          path: english.pdf
          if-no-files-found: error

      - name: Generate thumbnail (push to main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: pdftoppm english.pdf english-thumbnail -png -singlefile -scale-to 350

      - name: Upload thumbnail (push to main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: English-Thumbnail-${{ github.run_number }}
          path: english-thumbnail.png
          if-no-files-found: error

      - name: Publish release (push to main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            english.pdf
            english-thumbnail.png
          tag_name: latest
          draft: false
          prerelease: false