name: Build CV
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_typst_pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools and fonts
        run: |
          set -euxo pipefail
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            git fontconfig unzip poppler-utils \
            fonts-firacode fonts-dejavu
          git clone --depth=1 https://github.com/bBoxType/FiraSans.git /tmp/FiraSans
          sudo mkdir -p /usr/local/share/fonts/fira
          sudo find /tmp/FiraSans -type f \
            \( -iname "*.ttf" -o -iname "*.otf" \) \
            -exec cp -n {} /usr/local/share/fonts/fira/ \;
          sudo fc-cache -f

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Compile CV
        run: |
          set -euxo pipefail
          typst compile english.typ english.pdf

      - name: Upload PDF (PR or push)
        uses: actions/upload-artifact@v4
        with:
          name: English-PDF-${{ github.event_name }}-${{ github.run_number }}
          path: english.pdf
          if-no-files-found: error

      - name: Generate thumbnail (push to main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: pdftoppm english.pdf english-thumbnail -png -singlefile -scale-to 350

      - name: Upload thumbnail (push to main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: English-Thumbnail-${{ github.run_number }}
          path: english-thumbnail.png
          if-no-files-found: error

      - name: Publish release (push to main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            english.pdf
            english-thumbnail.png
          tag_name: latest
          draft: false
          prerelease: false
