name: Build CV
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build_typst_pdf:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install base fonts and tools
        run: |
          set -euxo pipefail
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            fonts-firacode fonts-dejavu fontconfig poppler-utils unzip jq
          sudo fc-cache -f

      - name: Install Fira Sans from Mozilla release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euxo pipefail
          # Get the first zip asset that contains Fira Sans from latest release
          ASSET_JSON="$(gh release view --repo mozilla/Fira --json assets)"
          URL="$(echo "$ASSET_JSON" \
            | jq -r '.assets[] | select((.name|test("(?i)fira[_-]?sans.*\\.zip$")))
                     | .url' | head -n1)"
          test -n "$URL"
          gh release download --repo mozilla/Fira --pattern "*Fira*Sans*.zip" \
            --output /tmp/FiraSans.zip --clobber
          sudo mkdir -p /usr/local/share/fonts/fira
          unzip -q /tmp/FiraSans.zip -d /tmp/fira
          sudo find /tmp/fira -type f -iregex '.*\.(ttf|otf)$' \
            -exec cp -n {} /usr/local/share/fonts/fira/ \;
          sudo fc-cache -f
          fc-list | grep -i 'fira' | head -n 30 || true

      - name: Setup Typst
        uses: typst-community/setup-typst@v4

      - name: Verify Typst sees Fira
        run: |
          set -euxo pipefail
          typst fonts | grep -Eiq '^fira (sans|code)' || {
            echo "Typst cannot see Fira fonts"; exit 1; }

      - name: Compile CV
        run: typst compile english.typ english.pdf

      - name: Upload artifact (PR or push)
        uses: actions/upload-artifact@v4
        with:
          name: English-PDF-${{ github.event_name }}-${{ github.run_number }}
          path: english.pdf
          if-no-files-found: error

      - name: Generate thumbnail (push to main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: pdftoppm english.pdf english-thumbnail -png -singlefile -scale-to 350

      - name: Upload thumbnail (push to main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: English-Thumbnail-${{ github.run_number }}
          path: english-thumbnail.png
          if-no-files-found: error

      - name: Publish release (push to main only)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            english.pdf
            english-thumbnail.png
          tag_name: latest
          draft: false
          prerelease: false
