name: Build CV
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build_typst_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Install fonts
        env:
          GH_TOKEN: ${{ github.token }} # Required by gh in GitHub Actions
        run: |
          # Install required tools and fonts available via apt
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends fonts-firacode poppler-utils unzip
          # Vendor fonts into workspace for the containerized Typst action
          mkdir -p .fonts
          # Copy Fira Code from system to vendored folder
          cp -n /usr/share/fonts/truetype/firacode/*.ttf .fonts/ 2>/dev/null || true
          # Download and vendor Fira Sans from upstream releases
          gh release download --repo mozilla/Fira --archive zip --output FiraSans.zip
          mkdir -p _fira
          unzip -q FiraSans.zip -d _fira
          find _fira -type f -iname "*FiraSans*.ttf" -exec cp -n {} .fonts/ \;
          # Optionally add DejaVu fallbacks
          cp -n /usr/share/fonts/truetype/dejavu/*.ttf .fonts/ 2>/dev/null || true
          # Show a few vendored fonts for debugging
          echo "Vendored fonts (sample):"
          ls -1 .fonts | grep -Ei "fira|dejavu" | head -n 20 || true
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Debug Typst font discovery
        uses: docker://ghcr.io/typst/typst:latest
        env:
          TYPST_FONT_PATHS: /github/workspace/.fonts:./.fonts
        with:
          args: fonts
      - uses: lvignoli/typst-action@main
        with:
          source_file: |
            english.typ
          options: |
            --font-path
            ./.fonts
        env:
          TYPST_FONT_PATHS: /github/workspace/.fonts:./.fonts
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: English PDF
          path: |
            english.pdf
      - name: Generate thumbnails
        run: |
          pdftoppm english.pdf english-thumbnail -png -singlefile -scale-to 350
      - name: Publish release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            english.pdf
            english-thumbnail.png
          tag_name: latest
          draft: false
          prerelease: false
