name: Build CV
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build_typst_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Install fonts
        env:
          GH_TOKEN: ${{ github.token }} # Required by gh in GitHub Actions
        run: |
          # Install required fonts and pdftoppm (fast path on Ubuntu)
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends \
            fonts-firacode \
            fonts-noto-core \
            fonts-noto-color-emoji \
            fonts-dejavu \
            poppler-utils
          # Copy fonts into workspace so container action can see them
          mkdir -p .fonts/noto .fonts/dejavu .fonts/firacode
          cp -r /usr/share/fonts/truetype/noto/* .fonts/noto/ 2>/dev/null || true
          cp -r /usr/share/fonts/opentype/noto/* .fonts/noto/ 2>/dev/null || true
          cp -r /usr/share/fonts/truetype/dejavu/* .fonts/dejavu/ 2>/dev/null || true
          cp -r /usr/share/fonts/truetype/firacode/* .fonts/firacode/ 2>/dev/null || true
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: lvignoli/typst-action@main
        with:
          source_file: english.typ
        env:
          TYPST_FONT_PATHS: ./.fonts/noto:./.fonts/dejavu:./.fonts/firacode
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: English PDF
          path: |
            english.pdf
      - name: Generate thumbnails
        run: |
          pdftoppm english.pdf english-thumbnail -png -singlefile -scale-to 350
      - name: Publish release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            english.pdf
            english-thumbnail.png
          tag_name: latest
          draft: false
          prerelease: false
